version: "3.0"
services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=localstack-access-key
      - AWS_SECRET_ACCESS_KEY=localstack-secret-key
      - LS_LOG=WARN
      - AWS_DEFAULT_REGION=us-east-1
      - HOSTNAME=localstack
    volumes:
      - ./script/create-local-s3-bucket.sh:/etc/localstack/init/ready.d/init-aws.sh

  itwc-back:
    container_name: itwc-back
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: local
    image: itwc-back
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs
    depends_on:
      - redis