version: "3.0"
services:
  db:
    container_name: h2
    image: oscarfonts/h2:latest
    restart: always
    ports:
      - 1521:1521
      - 8081:81
    environment:
      H2_OPTIONS: -ifNotExists
      restart: always
  itwc-back:
    container_name: itwc-back
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SPRING_PROFILES_ACTIVE: local
    image: itwc-back
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/logs