---
spring:
  config:
    activate:
      on-profile: local

external:
  member:
    host: http://localhost:8081
  world-cup-game:
    host: http://localhost:8080

---
spring:
  config:
    activate:
      on-profile: prod

external:
  member:
    host: http://192.168.25.38:8081
  world-cup-game:
    host: http://192.168.25.38:8080