server:
  port: 80
jasypt:
  encryptor:
    password: ${JASYPT_KEY}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${RDS_URL}
    username: ${RDS_USER_NAME}
    password: ${RDS_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: 6379
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

jwt:
  secret: ${JWT_SECRET}
  token-validity-milli-seconds:
    access: 360000 # 6분
    refresh: 1800000 # 30분

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
      cloud-watch:
        access-key: ${AWS_CLOUD_WATCH_ACCESS_KEY}
        secret-key: ${AWS_CLOUD_WATCH_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: itwc-file

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  config: classpath:log/logback-spring-prod.xml