spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    database: mysql   # 추가 해준 부분
    database-platform: org.hibernate.dialect.MySQL8Dialect # 추가 해준 부분
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: glgful8fLHILImISgmxcq123458C76wrqwmrnJFfn5585j3602r8rt29f9
  token-validity-milli-seconds:
    access: 20000
    refresh: 21600000
logging:
  config: classpath:log/logback-spring-${spring.profiles.active}.xml