spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/itwc?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 23g3g#232g@!

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}:3306/ITWC?serverTimezone=UTC&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}