server:
  port: 8080
jasypt:
  encryptor:
    password: my_jasypt_key
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
spring:
  config:
    import:
      - application-jwt.yml
      - application-feign.yml
      - application-db.yml
  redis:
    host: ENC(mKCkUmM/qBfmWsz4WQJvO8nefQtdwnQVhJCY7rrQ/YDq4kSArOyP0PQflOFb24dcIxpKKiTFcJzjsx3ws9gjPnGHlaqBWP95j1je3xY9x9iEIloRjc5dH/oyYzajnoLF) # PROD 변경
    port: 6379
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: itwc
        dialect: org.hibernate.dialect.MySQL57Dialect

jwt:
  secret: ENC(jNtfh8SGjyY4DfLK9eY9nh3cRVqVtzIWxj/2gYML7s+5rG8l1y5qbo7rIjO81qGUIMeVzHT7XP55zApSnajld9YTefQCtMMHr6eCezsLkgE82m6uian5+l1mPSSWrvyOEaEI/mjP3+tJArgBMVcNPO0S4oq6lJaBsMReL69jWautEInFdgz9vwGReKczh8FEGnMCuEgl+IzQMJXyxye7iMjsIqhvlFmblFtFBYq8FhgJf7ljsNKWcmrulIwF3JqA)
  token-validity-milli-seconds:
    access: 360000 # 6분
    refresh: 18000000 # 5시간

cloud:
  aws:
    credentials:
      access-key: ENC(L5nkU1CtIQA9bQqDHwwvEXjK8bj5q8xVig5RSdOdxQAJBYTHTdrRoaBPnc/UJ2n+HHaNDUFSlsfHf4MU0+RXCg==)
      secret-key: ENC(3BgK9UA4pc2pmPZjUZhh2jpMLh18dzFoQrrqVu7XbLW1iyVOo+05tv41DtxmqSV1JPnhMIDzADxhbSbRPuOLbhk75jdDr3niR9JrV3uqpuk=)
      cloud-watch:
        access-key: ENC(h3CIHsMbShh18XDAO2NATkJ6VAQqPNL66L2gBqv2qpYiVcZV5BEZYh6fZaIn4cXTMNp1RtocKUA/OcwEhkx/xg==)
        secret-key: ENC(R6QFldLtE3iYQB93pGU44V2wWTnMUHsBBSmpswoZOAwYHPe/rA7tIJUWTS3QLufz+UGKXxNlPFrttyh+Zdzr96H7f1mHllCYUzzI4ijIKwg=)
    end-point: not-used-in-prod-profile
    region: ap-northeast-2
    s3:
      bucket: itwc-file

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

origin:
  front: http://masikga.net

logging:
  config: classpath:log/logback-spring-prod.xml

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.masikga.itwc.domain